### ISSUE TITLE
how to use dbContext.Database.BeginTransaction()?

### ISSUE THREAD

**Issue by wanghaoxing** [cwoodruff/ChinookASPNETCoreAPINTier#14]
i like this architecture ,i want to know use dbContext.Database.BeginTransaction()? in domain

**Comment by cwoodruff** [comment]
@wanghaoxing interesting idea and will look at this

**Comment by cwoodruff** [comment]
@wanghaoxing I looked at DBContext Transactions https://docs.microsoft.com/en-us/ef/core/saving/transactions and I am not doing anything that would need transactions. I would use them when I add the ability to save associated data for an entity type.
