### ISSUE TITLE
newtonsoft json nuget is missing from Domain

### ISSUE THREAD

**Issue by Abrahamberg** [cwoodruff/ChinookASPNETCoreAPINTier#17]
Hello, 
Seems newtonsoft json nuget is missing from Domain. therefore it is not possible to build the solution.

**Comment by ericcoleman** [comment]
Just to piggyback on this, the Domain csproj has a reference to a Nuget package on your local computer. 

```    <Reference Include="FluentValidation, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7de548da2fbae0f0">
  <HintPath>..\..\..\..\Users\cwood\.nuget\packages\fluentvalidation\8.4.0\lib\netstandard2.0\FluentValidation.dll</HintPath>
    </Reference>```

**Comment by cwoodruff** [comment]
@Abrahamberg @ericcoleman thanks and both are fixed in Domain
