### ISSUE TITLE
Convert getter resulting POST and PUT now working

### ISSUE THREAD

**Issue by amansulaiman** [cwoodruff/ChinookASPNETCoreAPINTier#21]
I have been using your old repo for my App architecture. Recently I updated to 2.2, since then Post and PUT stop working.
Later I reliease that the Convert getter is actually what causing this Erro

> InsufficientExecutionStackException: Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space

After which I change the getter to a Method, then everything works fine. 
Please is there any harm in using Method for Convert instead of using getter

**Comment by cwoodruff** [comment]
Abdulrahman --

First I want to thank you for trusting my architecture for your work. There is no issue with changing the Getter to a Method. I am looking at it but would love to see your changes. Could you please send me a Pull Request with the code? Thanks!

Have a great day!

Woody

**Comment by amansulaiman** [comment]
Thank you, @cwoodruff  Woody
I have opened a pull request for that #22
