### ISSUE TITLE
Upgrade to .net core 3.1

### ISSUE THREAD

**Issue by mayureshs** [cwoodruff/ChinookASPNETCoreAPINTier#23]
Are there are any plans to upgrade to .NET Core 3.1 ?

**Comment by cwoodruff** [comment]
@mayureshs I have started a new repo for 3.1 at https://github.com/cwoodruff/ChinookASPNETCore3APINTier

I had to remove the async code due to big changes with it in 3.1. Updating the code for new async code.

**Comment by mayureshs** [comment]
Thanks !

**Comment by Kaushik-NP** [comment]
Are there any plan for data access using Dapper

**Comment by cwoodruff** [comment]
@Kaushik-NP thanks and yes I plan on migrating the Dapper to 3.1. Please keep an eye on the following repo https://github.com/cwoodruff/ChinookASPNETCore3APINTierDapper

**Comment by cwoodruff** [comment]
also @Kaushik-NP if you want .NET Core 2.2 web api with dapper look here https://github.com/cwoodruff/ChinookASPNETCoreAPINTierDapper

**Comment by Kaushik-NP** [comment]
@cwoodruff Any plan for multi-tenant (multi DB) architecture, I have used your architecture in my current project it's really awesome, now I need to implement multi-tenant for different clients could you help me on this, for configure the connection string.
